### PR TITLE
Improve non-monotonic array coordinates

### PR DESCRIPTION
**Pull request by jmilloy**
This PR includes
 - #120 segment length property
 - #162 non-monotonic area bounds
 - non-monotonic outer select
 - #168 default ctype for singleton coordinates
 - #103 proper handling of coordinate properties
 - read-only traits in Coordinates1d, ArrayCoordinates1d, UniformCoordinates1d, StackedCoordinates (see also #111)
 - enforces crs to be the same in all dimensions for StackedCoordinates and Coordinates.
 - `divide_delta` utility function (similar to `add_coord`)
 - #211 partially implemented custom JSONEncoder, used by Coordinates

### CODE REVIEW

**Comment by mpu-creare** [comment]
Do you want to include #162 in this PR?

**Comment by jmilloy** [comment]
I've broadened this PR, and marked it as WIP

**Comment by jmilloy** [comment]
@mpu-creare This feature is implemented, but SMAP should be updated. It may fail currently, or it may have workarounds that are no longer needed. Do you want me to take a look at that or can you do it?

**Comment by jmilloy** [comment]
@mlshapiro I've updated the coordinates for this feature and there is one compositor test failing: `test_compositor_implemented_functions`. Can you take a look at that? You may be able to fix it, or we just need to comment out that assertion for now.

**Comment by mpu-creare** [comment]
@jmilloy if you have time, please have a look... I'm swamped...

**Comment by mpu-creare** [comment]
@jmilloy I just confirmed that this still works with SMAP. I'm merging, and I'll make a new issue to update SMAP to use this functionality.

**Comment by mpu-creare** [comment]
Of course I'll figure out the failing unit test first...

**Comment by jmilloy** [comment]
So we should be able to close #120, #162, and #168.

(But I want to spend an hour or so on #211, for the next release)

**Pull request merged**
