### PR TITLE
WIP: Remove InterpolationMixin and update some of the tests.

### PR DESCRIPTION
**Pull request by jmilloy**

### CODE REVIEW

**Comment by jmilloy** [comment]
Removing the InterpolationMixin is a bit of a challenge, the tests rely on interpolation all over the place, and I've started to get into the algorithms which maybe have more problems. I made this a separate branch because I'm not entirely convinced that we should still do this.

**Comment by mpu-creare** [comment]
Sounds like we should talk.

**Comment by jmilloy** [comment]
I think we should keep the `InterpolationMixin`. It feels pretty weird to eval and get back different coordinates. I think we should rename `RasterioBase` etc to `RasterioRaw`, which feels more intentional.

I think we should also rename `DataCompositor` to `DataCompositorRaw` and `InterpDataCompositor` to `DataCompositor`.

Actually, I think we should remove the existing `TileCompositor` that never really worked, and rename the new data compositors to `TileCompositorRaw` and `TileCompositor`.

**Comment by mpu-creare** [comment]
I agree with the name suggestions. Please make it so!

**Comment by jmilloy** [comment]
We may not remove this after-all. Iceboxing.

**Comment by mpu-creare** [comment]
shall I close this?

**Comment by jmilloy** [comment]
Yep

**Pull request closed without merging**
