### PR TITLE
Feature/base ref set

### PR DESCRIPTION
**Pull request by CFoye-Creare**
Properly create `base_ref` property and add a setter.

### CODE REVIEW

**Comment by mpu-creare** [comment]
Looks like some child nodes overwrite `base_ref`, so this solution doesn't work.

**Review by mpu-creare — APPROVED** [review]
This all looks good.

**Comment by mpu-creare** [comment]
We'll merge this into main along with a few other changes to make a new release.

**Comment by rparker-creare** [comment]
We manually merged this into develop-3.X

**Pull request closed without merging**
