### PR TITLE
python black autoformatting

### LINKED ISSUE #272: code autoformatting
**Description**
Choose and deploy a code autoformatter.

**Describe the solution you'd like**
Python black (or a different autoformatter), with instructions and possibly configuration for running the autoformatting as a pre-commit hook.

### PR DESCRIPTION
**Pull request by jmilloy**
* Autoformats the entire project using python black.
 * Adds a `pyproject.toml` file with the black config. Notably: 120 character lines, and ignores setup.py.
 * Adds black and pre-commit dev requirements.
 * Adds a `pre-commit-config.yaml` file with a hook for black, and automatically install pre-commit hooks in develop mode
 * Adds a `black --check` job in TravisCI

Closes #272

### CODE REVIEW

**Comment by jmilloy** [comment]
@mpu-creare I just need to know whether to automatically install the pre-commit hooks or not in setup. You can see how that would be done in feature/black-auto-install-hook. And I need to update the dev docs, one way or the other.

**Comment by mpu-creare** [comment]
Yep, do it automatically on [devall] installation.

**Comment by jmilloy** [comment]
> [devall] installation

That's not possible. I can do it in local/develop mode (and not on a normal install mode), though.

**Comment by mpu-creare** [comment]
Okay, that's fine too. 

I just want to force developers to use it, so it should be as easy as possible.

**Comment by jmilloy** [comment]
@mlshapiro @mpu-creare @drc-creare @dsully1992 

I've added python black autoformating. You should re-install popdac after pulling develop, which will install the necessary dependencies and git hooks.

Alternatively, you can manually install pre-commit and black and manually install the pre-commit hooks:

```
$ pip install pre_commit black
$ pre-commit install
```

You will also probably need to run black autoformatting on your branches before merging to avoid unnecessary conflicts.

**Comment by mpu-creare** [comment]
How do you run black autoformatting on my branch?

**Comment by jmilloy** [comment]
Run `black podpac` from the root of the repo.

(`pyproject.toml` contains the config)

**Comment by mpu-creare** [comment]
the `.pre-commit-config.yaml` specifies Python3.6 -- but I'm using Python3.7, so it failed for me. Is there a way to specify more than one version?

**Comment by jmilloy** [comment]
Looks like we can specify just `python3`. Let's try that.

**Comment by jmilloy** [comment]
I pushed that change to develop. Maybe we can even leave the language_version out, though. Let me know if that change works for you.

**Comment by jmilloy** [comment]
Ah, it might help to run `black podpac -l 120` in your branch because you will not have the pyproject.toml config in your branch yet.

**Comment by jmilloy** [comment]
Okay - if you have a merge that is now particularly gnarly because of the autoformatting, go ahead and lob it my way and I'll try to get to it right away. It can be a tad tedious.

**Comment by mpu-creare** [comment]
The drought-monitor feature branch will be a bear -- there are multiple bug fixes on it (that really should have been split into smaller merges) so lots of code changes. I'm pretty much done with it though.

**Comment by mlshapiro** [comment]
lets merge it! I'm happy to help too.

Just poked around a little bit and it works  best to copy over `.pre-commit-config.yaml` and `pyproject.toml` to the drought-monitor branch and then then `black podpac`. 

From here the merge looks painful, but straightforward and clear.

**Comment by mpu-creare** [comment]
awesome. I'll make a PR.

**Pull request merged**
