### PR TITLE
Release/1.0.0

### PR DESCRIPTION
**Pull request by mlshapiro**
Initiate 1.0.0 release procedure

### CODE REVIEW

**Comment by mlshapiro** [comment]
Note to update README copy (potentially) with new stability message

**Comment by jmilloy** [comment]
We have a coverage issue. The two primary culprits are the caching and the data types, though the missed caching coverage is due to the S3 Cache, which may be the desired behavior. @mpu-creare Do we need to fix this so it is above 90% before we can release?

**Comment by jmilloy** [comment]
The S3CacheStore has been excluded from the coverage; there are tests but we do not run them in CI.

**Comment by mlshapiro** [comment]
Lambda function needs to get updated (see fix/aws)

**Comment by dsully1992** [comment]
If I'm not mistaken, the Lambda function update was the final roadblock for this release. That is done, so I believe we are good to go.

**Pull request closed without merging**
