### PR TITLE
API Audit

### PR DESCRIPTION
**Pull request by CFoye-Creare**

### CODE REVIEW

**Comment by CFoye-Creare** [comment]
Running tests after changing all appropriate modules to plural.

**Comment by CFoye-Creare** [comment]
merging from develop undid previous changes. reinstating refactoring of modules.

**Comment by CFoye-Creare** [comment]
All tests that should pass do.

**Comment by mpu-creare** [comment]
Also, I think the `version` module should be an exception? It should be singular, because that seems to be the common convention across Python libraries. @jxm, care to weigh in?

**Comment by CFoye-Creare** [comment]
I renamed modules inside podpac.* to plural, but changed modules inside podpac.*.* to singular. So, `podpac.interpolator.py` became `podpac.interpolators.py` while `podpac.interpolation.interpolator.interpolator.py` was kept singular. Want me to change `podpac.interpolation.*` to `podpac.interpolator`?

**Pull request closed without merging**
