### PR TITLE
clear cache method

### LINKED ISSUE #286: Method/Utility to clear cache
**Description**

We should add a small method to automatically clear the cache given the current podpac settings.

**Describe the solution you'd like**

A top level method that will clear the cache

**Sample Code**
```
from podpac.utils import clear_cache

clear_cache()  # deletes the contents of my current cache directory
```

### PR DESCRIPTION
**Pull request by jmilloy**
Adds a `clear_cache` method to `podpac.core.cache.cache_ctrl` along with a test. There is also a public reference at `podpac.utils.clear_cache`, and the user docs are updated accordingly.

I removed the `cached_property` and `clear_cache` util. The name clashed (both clear_cache specifically and `cache` in general). They were only used in one place (Rasterio), and I felt the indirection adds unnecessary load that's easier to mess up than to get right. This can generally be handled in-place using `traitlets.observe`, a simple private attribute, or with the existing builtin `functool.lru_cache`.

Closes #286

### CODE REVIEW

**Comment by jmilloy** [comment]
Note: test failures are due to Zarr, which is fixed elsewhere.

**Comment by mlshapiro** [comment]
@jmilloy do you mind to merge in develop before I review? I think you will know better what changed since its mostly the auto-formatting.

**Comment by jmilloy** [comment]
@mlshapiro I have errors I need to look into now, anyways.

**Comment by jmilloy** [comment]
@mlshapiro Okay, yeah, I don't know how to make this easier to compare. I'll go ahead and merge, but you can take a look at the second commit (and maybe the first commit) to see the changes more clearly.

**Pull request merged**
